config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'welcome#index'
  get 'welcome/api' => 'welcome#api'
  get 'locations/api' => 'locations#api'
  get 'movies/api' => 'movies#api'
  get 'users/api' => 'users#api'
  get 'scenes/api' => 'scenes#api'

get 'dashboards' => 'dashboards#index'
get 'quickvisits' => 'quickvisits#index'
resources :users

resources :locations do
  resources :scenes
end

resources :movies do
  resources :scenes
end

resources :scenes do
  resources :visits
end

resources :visits, shallow: true do
  resources :photos do
    resources :likes
    resources :comments
  end
end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :photo
  belongs_to :user

  validates_length_of :remark, :minimum => 1, :message => "Can't create a comment without a string!"

end

app/models/like.rb
class Like < ActiveRecord::Base

  belongs_to :photo
  belongs_to :user

end

app/models/location.rb
class Location < ActiveRecord::Base

  belongs_to :user
  has_many :scenes

end

app/models/movie.rb
class Movie < ActiveRecord::Base

  has_many :scenes

end

app/models/photo.rb
class Photo < ActiveRecord::Base

  belongs_to :visit
  has_many :likes
  has_many :comments

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/bond.jpg", bucket: 'moviesnaps', :url => ':s3_domain_url', :path => '/:class/:attachment/:id_partition/:style/:filename'
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/scene.rb
class Scene < ActiveRecord::Base

  belongs_to :movie
  belongs_to :location
  has_many :visits

  validates_length_of :movie_id, :minimum => 1, :message => "Can't create a scene without a movie!"
  validates_length_of :location_id, :minimum => 1, :message => "Can't create a scene without a location!"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :locations
  has_many :visits
  has_many :likes
  has_many :comments
  has_many :visited_scenes, through: :visits, source: :scene

  def self.from_omniauth(auth)
    where(provider: auth['provider'], uid: auth['uid']).first_or_create do |user|
      user.email = auth['info']['email']
      user.password = Devise.friendly_token[0,20]
      user.name = auth['info']['name']   # assuming the user model has a name
      user.image = auth['info']['image'] # assuming the user model has an image
    end
  end

end

app/models/visit.rb
class Visit < ActiveRecord::Base

  has_many :photos
  belongs_to :scene
  belongs_to :user
  accepts_nested_attributes_for :photos

  validates_date :date_visited, :on_or_before => lambda { Date.current }
  validates_length_of :description, :maximum => 40, :minimum => 1, :message => "Uh oh! You have over 40 characters!"

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @photo = Photo.find(params[:photo_id])
    @photo.likes.create(user_id: current_user.id)
    render json: {new_like_count: @photo.likes.count}
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def create
    film_name = params[:name]
    location = params[:location]
    film = Movie.create(name: film_name)
    scene = Scene.create(movie_id: film.id, location_id: location)
    redirect_to new_scene_visit_path(scene.id)
  end

  def index
  end

  def show
    @movie = Movie.find(params[:id])
    @comment = Comment.new
  end

  def api
    @movies = Movie.all
    render json: @movies.to_json
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/quickvisits_helper.rb
module QuickvisitsHelper
end

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/movies/index.html.erb
<h1>Search for movies</h1>
<input id="enterMovie" placeholder="Enter a movie" type="text" size="40" onkeydown="acquireMovies()"/>
<div><button id="select-movie">Select Movie</button><span id="noResultsMsg">Movie not yet in database</span></div>

app/views/movies/show.html.erb
<section id="movieProfile">

  <div id='title'><h2><%= @movie.name %></h2></div>

  <div id='movie_img'></div>

  <div id="scenes">
    <% if @movie.scenes.any? %>
      Scenes:
      <ul class="scenes">
        <% @movie.scenes.reverse.each do |scene| %>
          <li class="scene">
            <%= link_to scene.location.address, location_path(scene.location) %>
            </br>
            Scene photo:<%= image_tag scene.image_file_name %>
            <div class="mapBox">
              <div class="mapDestination" id="mapDestination-<%= scene.id %>">
              </div>
            </div>
            <div class="longitude"><%= scene.location.longitude %></div>
            <div class="latitude"><%= scene.location.latitude %></div>
            </br>
            <% if scene.visits.any? %>
              Visitors:
              <ul class="visits">
                <% scene.visits.order('date_visited desc').each do |visit| %>
                  <li class="visit">
                    <%= image_tag visit.user.image, :class => "user_img" %>
                    <%= link_to visit.user.name, user_path(visit.user) %>
                    <% if visit.date_visited %> visited on <%= visit.date_visited.strftime('%e %B %Y') %><% end %>
                    <% if visit.description %> ("<%= visit.description %>")<% end %></br>
                    <% if visit.photos.any? %>
                      <ul class="photos">
                        <% visit.photos.each do |photo| %>
                          <li class="photo">
                            <%= image_tag photo.image.url, :class => "user_scene_img" %>
                            <%= photo.caption %>
                            <% if current_user %>
                              <% liked = false %>
                                <% photo.likes.each do |l| %>
                                  <% if current_user.id == l.user_id %>
                                    <% liked = true %>
                                    <% break %>
                                  <% end %>
                                <% end %>
                                <% if liked == false %>

                                <%= link_to "♡", photo_likes_path(photo), class: 'likes-link' %>

                                <% end %>

                                <span class='likes_count'> <%= photo.likes.count %> </span> <%= 'like'.pluralize photo.likes.count %>
                              <%= render partial: "partials/commentform", locals: {photo: photo} %>
                            <% end %>
                            <% if photo.comments.any? %>
                              <ul class="comments">
                                <% photo.comments.order('created_at desc').each do |comment| %>
                                  <li class="comment">
                                    <%= image_tag comment.user.image %>
                                    <%= link_to comment.user.name, user_path(comment.user) %>:
                                    <%= comment.remark %>
                                    (<%= comment.created_at.strftime('%e %B %Y at %H:%M') %>)
                                  </li>
                                <% end %>
                              </ul>
                            <% end %>
                          </li>
                        <% end %>
                      </ul>
                    <% else %>
                      No photos relating to this visit available
                    <% end %>
                  </li>
                <% end %>
              </ul>
            <% else %>
              No visits relating to this scene available
            <% end %>
          </li>
        <% end %>
      </ul>
    <% else %>
      No scenes for this movie available
    <% end %>
  </div>

</section>