config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'welcome#index'
  get 'welcome/api' => 'welcome#api'
  get 'locations/api' => 'locations#api'
  get 'movies/api' => 'movies#api'
  get 'users/api' => 'users#api'
  get 'scenes/api' => 'scenes#api'

get 'dashboards' => 'dashboards#index'
get 'quickvisits' => 'quickvisits#index'
resources :users

resources :locations do
  resources :scenes
end

resources :movies do
  resources :scenes
end

resources :scenes do
  resources :visits
end

resources :visits, shallow: true do
  resources :photos do
    resources :likes
    resources :comments
  end
end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :photo
  belongs_to :user

  validates_length_of :remark, :minimum => 1, :message => "Can't create a comment without a string!"

end

app/models/like.rb
class Like < ActiveRecord::Base

  belongs_to :photo
  belongs_to :user

end

app/models/location.rb
class Location < ActiveRecord::Base

  belongs_to :user
  has_many :scenes

end

app/models/movie.rb
class Movie < ActiveRecord::Base

  has_many :scenes

end

app/models/photo.rb
class Photo < ActiveRecord::Base

  belongs_to :visit
  has_many :likes
  has_many :comments

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/bond.jpg", bucket: 'moviesnaps', :url => ':s3_domain_url', :path => '/:class/:attachment/:id_partition/:style/:filename'
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/scene.rb
class Scene < ActiveRecord::Base

  belongs_to :movie
  belongs_to :location
  has_many :visits

  validates_length_of :movie_id, :minimum => 1, :message => "Can't create a scene without a movie!"
  validates_length_of :location_id, :minimum => 1, :message => "Can't create a scene without a location!"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :locations
  has_many :visits
  has_many :likes
  has_many :comments
  has_many :visited_scenes, through: :visits, source: :scene

  def self.from_omniauth(auth)
    where(provider: auth['provider'], uid: auth['uid']).first_or_create do |user|
      user.email = auth['info']['email']
      user.password = Devise.friendly_token[0,20]
      user.name = auth['info']['name']   # assuming the user model has a name
      user.image = auth['info']['image'] # assuming the user model has an image
    end
  end

end

app/models/visit.rb
class Visit < ActiveRecord::Base

  has_many :photos
  belongs_to :scene
  belongs_to :user
  accepts_nested_attributes_for :photos

  validates_date :date_visited, :on_or_before => lambda { Date.current }
  validates_length_of :description, :maximum => 40, :minimum => 1, :message => "Uh oh! You have over 40 characters!"

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @photo = Photo.find(params[:photo_id])
    @photo.likes.create(user_id: current_user.id)
    render json: {new_like_count: @photo.likes.count}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @visits = Visit.where("user_id = ?", @user.id)
    @comment = Comment.new
  end

  def index
  end

  def api
    @users = User.all
    render json: @users.to_json
  end

end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController

  def index
    @scenes = Scene.all
    @visits = Visit.all
  end

  def new
    @scene = Scene.find(params[:scene_id])
    @location = Location.find(@scene.location_id)
    @current_visits = Visit.where("scene_id = ?", params[:scene_id]).all
    @visit = Visit.new
    @movie = @scene.movie.name
    @photo = Photo.new
  end

  def create
    @visit = Visit.create(visit_params.merge({user:current_user}).merge({scene_id: params[:scene_id]}))
    @photo = Photo.create(photo_params.merge({visit_id: @visit.id}))
    redirect_to root_path
  end

  def visit_params
    params.require(:visit).permit![:visit]
  end

  def photo_params
    params.require(:visit).permit![:photo]
  end

end

    # def new
    # @location = Location.where("latitude = ? AND longitude = ? AND address = ?", params[:posa], params[:posf], params[:address])
    # @movie = Movie.where("name = ?", params[:film])
    # @scene = Scene.where("location_id = ? AND movie_id = ?", @location.id, @movie.id)
    # # @scene = Scene.find(params[:scene_id])
    # # @location = Location.find(@scene.location_id)
    # # @current_visits = Visit.where("scene_id = ?", params[:scene_id]).all
    # @visit = Visit.new
    # # @movie = @scene.movie.name
    # # @photo = Photo.new
    # end

  # def new
  #   if params[:scene_id] == 0
  #     raise "go off and create a movie, location and scene"
  #   end
  #   @scene = Scene.find(params[:scene_id])
  #   @location = Location.find(@scene.location_id)
  #   @current_visits = Visit.where("scene_id = ?", params[:scene_id]).all
  #   @visit = Visit.new
  #   @movie = @scene.movie.name
  #   @photo = Photo.new
  # end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/quickvisits_helper.rb
module QuickvisitsHelper
end

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/visits/index.html.erb
<h1> temporarily this is a seperate screen </h1>
Current Scenes
<% if @scenes.any? %>
  <% @scenes.each do |scene| %>
    movie poster, name, location
    <%= scene.id %>
    <% if current_user %>
      <%= link_to "Add a visit", new_scene_visit_path(scene.location_id, scene.id) %>
    <% end %>
  <% end %>
<% else %>
  <h1>No visits yet</h1>
<% end %>
<br>


Curent Visits
<% if @visits.any? %>
  <% @visits.each do |visit| %>
    <%= link_to visit.description, scene_visit_path(visit.scene_id,visit) %>
  <% end %>
<% else %>
  <h1>No visits yet</h1>
<% end %>
<br>


<% if current_user %>
  <!-- If no scene exists, and you want to create a movie, location and scene as well as a visit -->
  <%= link_to "Add a visit", new_scene_visit_path(0) %>
<% end %>

app/views/visits/new.html.erb
<script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js'></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<div class="form-group">
  <div class="row">
    <div class="col-md-4"><br>
      <center><div id="movie_name"><h3><%= @movie %></h3></div>
      <div id='movie_img'></div></center>
    </div>
    <div class="col-md-4">
      <center><h3><%= @location.address %></h3>
      <br>
      <%= form_for [@scene, @visit] do |f| %>
        <%= f.fields_for :visit do |v| %>
          <%= v.label 'Tell us something about your visit:' %>
          <br>
          <%= v.text_field :description %>
          <br><br>
          <%= v.label 'Date visited:' %>
          <br>
          <%= v.date_select :date_visited, order: [:day, :month, :year] %>
          <br>
        <% end %>
        <br>
        <%= f.fields_for :photo, html: {multipart: true} do |builder| %>
          <%= builder.label 'Add your caption...' %>
          <br>
          <%= builder.text_field :caption %>
          <br><br>
          <%= builder.label 'Upload your image:' %>
          <%= builder.file_field :image %>
        <% end %>
        <br><br>
        <%= f.button :Submit %>
      <% end %></center>
    </div>
    <div class="col-md-4">
      <div id='preview'></div>
    </div>
  </div>
</div>