config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'welcome#index'
  get 'welcome/api' => 'welcome#api'
  get 'locations/api' => 'locations#api'
  get 'movies/api' => 'movies#api'
  get 'users/api' => 'users#api'
  get 'scenes/api' => 'scenes#api'

get 'dashboards' => 'dashboards#index'
get 'quickvisits' => 'quickvisits#index'
resources :users

resources :locations do
  resources :scenes
end

resources :movies do
  resources :scenes
end

resources :scenes do
  resources :visits
end

resources :visits, shallow: true do
  resources :photos do
    resources :likes
    resources :comments
  end
end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :photo
  belongs_to :user

  validates_length_of :remark, :minimum => 1, :message => "Can't create a comment without a string!"

end

app/models/like.rb
class Like < ActiveRecord::Base

  belongs_to :photo
  belongs_to :user

end

app/models/location.rb
class Location < ActiveRecord::Base

  belongs_to :user
  has_many :scenes

end

app/models/movie.rb
class Movie < ActiveRecord::Base

  has_many :scenes

end

app/models/photo.rb
class Photo < ActiveRecord::Base

  belongs_to :visit
  has_many :likes
  has_many :comments

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/bond.jpg", bucket: 'moviesnaps', :url => ':s3_domain_url', :path => '/:class/:attachment/:id_partition/:style/:filename'
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/scene.rb
class Scene < ActiveRecord::Base

  belongs_to :movie
  belongs_to :location
  has_many :visits

  validates_length_of :movie_id, :minimum => 1, :message => "Can't create a scene without a movie!"
  validates_length_of :location_id, :minimum => 1, :message => "Can't create a scene without a location!"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :locations
  has_many :visits
  has_many :likes
  has_many :comments
  has_many :visited_scenes, through: :visits, source: :scene

  def self.from_omniauth(auth)
    where(provider: auth['provider'], uid: auth['uid']).first_or_create do |user|
      user.email = auth['info']['email']
      user.password = Devise.friendly_token[0,20]
      user.name = auth['info']['name']   # assuming the user model has a name
      user.image = auth['info']['image'] # assuming the user model has an image
    end
  end

end

app/models/visit.rb
class Visit < ActiveRecord::Base

  has_many :photos
  belongs_to :scene
  belongs_to :user
  accepts_nested_attributes_for :photos

  validates_date :date_visited, :on_or_before => lambda { Date.current }
  validates_length_of :description, :maximum => 40, :minimum => 1, :message => "Uh oh! You have over 40 characters!"

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @photo = Photo.find(params[:photo_id])
    @photo.likes.create(user_id: current_user.id)
    render json: {new_like_count: @photo.likes.count}
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @photos = Photo.last(8).reverse
    @comment = Comment.new
    popular_group = Like.group(:photo_id).count.first(3)
    @popular = []
    popular_group.each { |p| @popular << Photo.find(p.first) }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/quickvisits_helper.rb
module QuickvisitsHelper
end

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<header>
  <% if flash[:notice] %>
    <div id='notice'>
      <center><h3><div class="alert alert-success" role="alert"><%= flash[:notice] %></div></h3></center>
  <% end %>
</header>
<script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js'></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<div id="myCarousel" class="carousel slide">

  <!-- Carousel items -->
  <div class="carousel-inner">
    <% if @popular.length == 3 %>
      <div class="active item">
        <img class="first-slide" src='<%= @popular[0].image.url %>'>
        <div class="container">
          <div class="carousel-caption">
            <h3><%= @popular[0].visit.scene.movie.name %></h3>
            <h4><%= @popular[0].caption %> <i><%= @popular[0].visit.user.name %></h4></i>
          </div><!-- carousel-caption -->
        </div><!-- container  -->
      </div><!-- active item  -->

      <div class="item">
        <img class="second-slide" src='<%= @popular[1].image.url %>'>
        <div class="container">
            <div class="carousel-caption">
              <h3><%= @popular[1].visit.scene.movie.name %></h3>
              <h4><%= @popular[1].caption %> <i><%= @popular[0].visit.user.name %></h4></i>
            </div><!-- carousel-caption  -->
        </div><!-- container  -->
      </div><!-- item  -->

      <div class="item">
        <img class="third-slide" src='<%= @popular[2].image.url %>'>
        <div class="container">
            <div class="carousel-caption">
              <h3><%= @popular[2].visit.scene.movie.name %></h3>
              <h4><%= @popular[2].caption %> <i><%= @popular[0].visit.user.name %></h4></i>
            </div><!-- carousel-caption -->
        </div><!-- container -->
      </div><!-- item -->
    <% end %>
  </div><!-- carousel-inner -->

  <!-- Carousel nav -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>

  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div><!-- carousel slide  -->

<aside id="welcomeAside" class="clearfix">

  <div style="width:45%;margin:0 auto; padding-top.5em;">
    <header style="margin-bottom:20px;margin-left:-5px;">
      <h2>What movie have you been in?</h2>
    </header>
        <div class="btn-group" >

          <a href="<%= new_scene_path %>"><button style="padding:1em 5em; margin-left:20px;" type="button" class="btn btn-primary btn-lg" >Upload photos</button></a>
        </div>
  </div>

</aside><!-- welcomeAside  -->

<section class="welcomeMainContent clearfix">
  <h2>Most recent uploads</h2>
  <% if @photos %>

          <% @photos.each do |p| %>
          <article>

            <div class="box"  title="<%= p.caption %>">

              <h4><%= p.caption %></h4>
              <figure>
                <a href="#">
                  <img src='<%= p.image.url %>' height='200' width='198' %>
                </a>
              </figure>

              <h6><i>Uploaded on </i> <%= p.created_at %></h6>

              <div class="likes">
                <% if current_user %>
                  <% liked = false %>
                  <% p.likes.each do |l| %>
                    <% if current_user.id == l.user_id %>
                      <% liked = true %>
                      <% break %>
                    <% end %>
                  <% end %>
                  <% if liked == false %>

                  <%= link_to "♡", photo_likes_path(p), class: 'likes-link' %>

                  <% end %>

                  <span class='likes_count'> <%= p.likes.count %> </span> <%= 'like'.pluralize p.likes.count %>

                <% end %>
              </div>

              <p>From the movie <%= p.visit.scene.movie.name %></p>

            </div>
            </article>
          <% end %>

    <% else %>
      No photos have been uploaded!
    <% end %>

</section> <!-- welcomeMainContent  -->